### ISSUE TITLE
Please Helpme

### ISSUE THREAD

**Issue by jairforero** [dhogborg/gosser#1]
# github.com/dhogborg/gosser
dhogborg\gosser\main.go:29:5: app.Author undefined (type *cli.App has no field or method Author)
dhogborg\gosser\main.go:30:5: app.Email undefined (type *cli.App has no field or method Email)
dhogborg\gosser\main.go:34:13: c.GlobalBool undefined (type *cli.Context has no field or method GlobalBool)
dhogborg\gosser\main.go:39:23: c.GlobalString undefined (type *cli.Context has no field or method GlobalString)
dhogborg\gosser\main.go:54:11: c.GlobalInt undefined (type *cli.Context has no field or method GlobalInt)
dhogborg\gosser\main.go:57:25: c.GlobalString undefined (type *cli.Context has no field or method GlobalString)
dhogborg\gosser\main.go:60:7: c.GlobalBool undefined (type *cli.Context has no field or method GlobalBool)
dhogborg\gosser\main.go:60:35: c.GlobalString undefined (type *cli.Context has no field or method GlobalString)
dhogborg\gosser\main.go:69:7: c.GlobalString undefined (type *cli.Context has no field or method GlobalString)
dhogborg\gosser\main.go:76:8: c.GlobalInt undefined (type *cli.Context has no field or method GlobalInt)

**Comment by dhogborg** [comment]
Some imports have changed name. Updated them and enabled go mod. Pull the latest changes, should work as expected now.

**Comment by jairforero** [comment]
Thanks! but no work
# github.com/dhogborg/gosser
dhogborg\gosser\main.go:29:5: app.Author undefined (type *cli.App has no field or method Author)
dhogborg\gosser\main.go:30:5: app.Email undefined (type *cli.App has no field or method Email)
dhogborg\gosser\main.go:34:13: c.GlobalBool undefined (type *cli.Context has no field or method GlobalBool)
dhogborg\gosser\main.go:39:23: c.GlobalString undefined (type *cli.Context has no field or method GlobalString)
dhogborg\gosser\main.go:54:11: c.GlobalInt undefined (type *cli.Context has no field or method GlobalInt)
dhogborg\gosser\main.go:57:25: c.GlobalString undefined (type *cli.Context has no field or method GlobalString)
dhogborg\gosser\main.go:60:7: c.GlobalBool undefined (type *cli.Context has no field or method GlobalBool)
dhogborg\gosser\main.go:60:35: c.GlobalString undefined (type *cli.Context has no field or method GlobalString)
dhogborg\gosser\main.go:69:7: c.GlobalString undefined (type *cli.Context has no field or method GlobalString)
dhogborg\gosser\main.go:76:8: c.GlobalInt undefined (type *cli.Context has no field or method GlobalInt)
dhogborg\gosser\main.go:76:8: too many errors

**Comment by jairforero** [comment]
I run
go get github.com/dhogborg/gosser
this is ok? Very thanks!
